from typing import TYPE_CHECKING, Protocol


if TYPE_CHECKING:
    from event_shortener.dto.short_url import ShortUrlDTO, UpsertShortUrlDTO


class IShortUrlDBAdapter(Protocol):
    async def get_by_external_id(self, external_id: str) -> ShortUrlDTO | None: ...

    async def get_by_ident(self, ident: str) -> ShortUrlDTO | None: ...

    async def insert(self, ident: str, dto: UpsertShortUrlDTO) -> ShortUrlDTO: ...

    async def update_by_external_id(self, old_external_id: str, dto: UpsertShortUrlDTO) -> ShortUrlDTO | None: ...

    async def delete_by_external_id(self, external_id: str) -> bool: ...

    async def increment_click(self, ident: str) -> None: ...


class IShortenerController(Protocol):
    async def shorten(self, dto: UpsertShortUrlDTO) -> tuple[str, bool]: ...

    async def get_ident(self, external_id: str) -> str | None: ...

    async def update(self, old_external_id: str, dto: UpsertShortUrlDTO) -> str | None: ...

    async def delete(self, external_id: str) -> bool: ...

    async def resolve(self, ident: str) -> ShortUrlDTO | None: ...

    async def register_click(self, ident: str) -> None: ...
